[package]
name = "machine_setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempfile = "3.3"

[dependencies]
ergo_fs = "0.2"
yaml-rust = "0.4"

