[package]
name = "machine_setup"
version = "0.2.4"
edition = "2021"
authors = ["Timo Prüße <chroma91@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A tool for configuring and setting up your machine."
readme = "README.md"
homepage = "https://github.com/Chroma91/machine-setup"
repository = "https://github.com/Chroma91/machine-setup"
keywords = ["cli", "machine", "setup", "configure"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempfile = "3.3"
dirs = "4"

[dependencies]
rand = "0.8"
ergo_fs = "0.2"
yaml-rust = "0.4"
symlink = "0.1"
git_commands = "0.2"
clap = { version = "3", features = ["derive"] }
ansi_term = "0.12"
