on:
  repository_dispatch:
    types: [create-release]

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.REPO_TOKEN}}
          workflow: build.yml

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**.zip"
          tag: ${{ github.event.client_payload.version }}
          token: ${{ secrets.REPO_TOKEN }}
