on:
  workflow_run:
    workflows: ["Builds"]
    types:
      - completed

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.REPO_TOKEN}}
          workflow: build.yml

      - uses: softprops/action-gh-release@v1
        with:
          files: "**-x86_64-**"
